#!/bin/bash
set -e
BIND_ADDRESS="0.0.0.0"
PUBLIC_PATH="public"
LOG_DIR="."
DATASTORE_LOCATION="./"
FILESTORE_DIRECTORY="./"
CLIENT_DIR="/velociraptor/clients"

# Move binaries into place
cp /opt/velociraptor/linux/velociraptor_client /velociraptor/velociraptor && chmod +x /velociraptor/velociraptor
mkdir -p $CLIENT_DIR/linux && rsync -a /opt/velociraptor/linux/velociraptor* /velociraptor/clients/linux/
mkdir -p $CLIENT_DIR/mac && rsync -a /opt/velociraptor/mac/velociraptor_client* /velociraptor/clients/mac/
mkdir -p $CLIENT_DIR/windows && rsync -a /opt/velociraptor/windows/velociraptor_client* /velociraptor/clients/windows/

# If no existing server config, set it up
if [ ! -f server.config.yaml ]; then
    ./velociraptor config generate > server.config.yaml --merge '{"Frontend":{"public_path":"'$PUBLIC_PATH'", "hostname":"'$VELOX_FRONTEND_HOSTNAME'", "require_client_certificates":true, "artifact_definitions_directory":"/tmp/artifacts/", "initial_server_artifacts":["Server.Import.ArtifactExchange","Server.Import.Extras","Server.Import.DetectRaptor"]},"API":{"bind_address":"'$BIND_ADDRESS'"},"GUI":{"bind_address":"'$BIND_ADDRESS'"},"Monitoring":{"bind_address":"'$BIND_ADDRESS'"},"Logging":{"output_directory":"'$LOG_DIR'","separate_logs_per_component":true}, "Client":{"use_self_signed_ssl":true, "ws_ping_wait_sec": 30, "concurrency": 2}, "Datastore":{"location":"'$DATASTORE_LOCATION'", "filestore_directory":"'$FILESTORE_DIRECTORY'", "min_allowed_file_space_mb":20000, "compression": "none"}, "defaults":{"notebook_cell_timeout_min":20, "notebook_number_of_local_workers":20, "hunt_expiry_hours":336, "max_in_memory_group_by": 60000, "notebook_versions": 20}}'
    # create account
    ./velociraptor --config server.config.yaml user add $VELOX_USER $VELOX_PASSWORD --role $VELOX_ROLE
    # do mtls stuff
    ./velociraptor --config server.config.yaml config api_client --name "Client" /velociraptor/velociraptor-mtls.yaml
    sleep 1
    # split the cert
    awk '/^client_cert: \|/ { flag=1; next } /^[^ ]/ { flag=0 } flag { sub(/^  /, ""); print }' /velociraptor/velociraptor-mtls.yaml > /velociraptor/client_cert.pem
    awk '/^client_private_key: \|/ { flag=1; next } /^[^ ]/ { flag=0 } flag { sub(/^  /, ""); print }' /velociraptor/velociraptor-mtls.yaml > /velociraptor/client_private_key.pem
    ./velociraptor --config server.config.yaml config show --config.client-crypto-client-certificate="$(</velociraptor/client_cert.pem)" --config.client-crypto-client-certificate-private-key="$(</velociraptor/client_private_key.pem)"  > /tmp/server.config.yaml
    mv /tmp/server.config.yaml /velociraptor/
    sed -i '/- https:\/\/localhost:8000/d' server.config.yaml
    sed -i 's#/tmp/velociraptor#.#'g server.config.yaml
fi

# Check Server Certificate Status, Re-generate if it's expiring in 24-hours or less

if true | ./velociraptor --config server.config.yaml config show --json | jq -r .Frontend.certificate | openssl x509 -text -enddate -noout -checkend 86400 >/dev/null; then
    echo "Skipping renewal, certificate is not expired"
else
    echo "Certificate is expired, rotating certificate."
    ./velociraptor --config ./server.config.yaml config rotate_key > /tmp/server.config.yaml
    cp ./server.config.yaml ./server.config.yaml.bak
    mv /tmp/server.config.yaml /velociraptor/.
fi
# Re-generate client config in case server config changed
./velociraptor --config server.config.yaml config client > client.config.yaml

# Repack clients
# Linux
./velociraptor config repack --exe clients/linux/velociraptor_client client.config.yaml /velociraptor/clients/linux/velociraptor_client_repacked
./velociraptor --config client.config.yaml debian client --output /velociraptor/clients/linux/
./velociraptor --config client.config.yaml debian client --binary /velociraptor/clients/linux/velociraptor_client_arm --output /velociraptor/clients/linux/
./velociraptor --config client.config.yaml debian client --binary /velociraptor/clients/linux/velociraptor_client_musl --output /velociraptor/clients/linux/
./velociraptor --config client.config.yaml rpm client --binary /velociraptor/clients/linux/velociraptor_client_musl --output /velociraptor/clients/linux/
./velociraptor --config client.config.yaml rpm client --output /velociraptor/clients/linux/
./velociraptor --config client.config.yaml rpm client --binary /velociraptor/clients/linux/velociraptor_client_arm --output /velociraptor/clients/linux/
# windows
./velociraptor config repack --exe /velociraptor/clients/windows/velociraptor_client_legacy64.exe  client.config.yaml /velociraptor/clients/windows/velociraptor_client_legacy64_repacked.exe
./velociraptor config repack --exe /velociraptor/clients/windows/velociraptor_client_legacy32.exe  client.config.yaml /velociraptor/clients/windows/velociraptor_client_legacy32_repacked.exe
./velociraptor config repack --exe /velociraptor/clients/windows/velociraptor_client.exe client.config.yaml /velociraptor/clients/windows/velociraptor_client_repacked.exe
./velociraptor config repack --msi /velociraptor/clients/windows/velociraptor_client.msi client.config.yaml /velociraptor/clients/windows/velociraptor_client_repacked.msi
./velociraptor config repack --msi /velociraptor/clients/windows/velociraptor_client_32.msi client.config.yaml /velociraptor/clients/windows/velociraptor_client_repacked_32.msi

# Start Velocoraptor
./velociraptor --config server.config.yaml frontend -v
